basePath: /api/v1
definitions:
  model.User:
    properties:
      email:
        type: string
      names:
        type: string
      password:
        maxLength: 50
        minLength: 6
        type: string
      username:
        maxLength: 50
        minLength: 3
        type: string
    required:
    - email
    - password
    - username
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: m3schroder@gmail.com
    name: Matthew Schroder
  description: Base setup for swagger
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: App API Docs
  version: "1.0"
paths:
  /user:
    post:
      consumes:
      - application/json
      description: Get a user by id
      parameters:
      - description: User Model
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.User'
      produces:
      - application/json
      responses: {}
      summary: Get a user
      tags:
      - accounts
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
